baseURL = 'https://claviersdanslesmonts.fr'
languageCode = 'fr'
title = 'Claviers Dans Les Monts'
theme = 'cdlm'
defaultContentLanguage = 'fr'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menus]
  [[menus.main]]
    name = 'À propos'
    pageRef = '/current/a-propos'
    weight = 1
  [[menus.main]]
    name = 'Artistes'
    pageRef = '/artistes'
    weight = 2
  [[menus.main]]
    name = 'Programme'
    pageRef = '/current/programme'
    weight = 3
  [[menus.main]]
    name = 'Éditions précédentes'
    pageRef = '/editions-precidentes'
    weight = 4
  [[menus.main]]
    name = 'Presse'
    pageRef = '/presse'
    weight = 5
  [[menus.main]]
    name = 'Ensemble Cobalt'
    pageRef = '/cobalt'
    weight = 6
  [[menus.main]]
    name = 'Stage du piano'
    pageRef = '/current/stage'
    weight = 7


