baseURL = 'https://claviersdanslesmonts.fr'
languageCode = 'fr'
title = 'Claviers Dans Les Monts'
theme = 'cdlm'
defaultContentLanguage = 'fr'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
