baseURL = 'https://spiffy-crostata-07a2fe.netlify.app'
languageCode = 'fr'
title = 'Claviers Dans Les Monts'
theme = 'cdlm'
defaultContentLanguage = 'fr'
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
