backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
locale: 'fr'
media_folder: static/img
public_folder: /img
collections:
  - name: 'mentions-legales'
    label: 'Mentions légales'
    files:
      - name: 'Mentions légales'
        label: 'Mentions légales'
        file: 'content/mentions-legales.md'
        create: false
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'a-propos'
    label: 'À propos'
    files:
      - name: 'à propos'
        label: 'À propos'
        file: 'content/a-propos.md'
        create: false
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'plan-du-site'
    label: 'plan du site'
    files:
      - name: 'plan-du-site'
        label: 'Plan du site'
        file: 'content/plan-du-site.md'
        create: false
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'FAQ'
    label: 'FAQ'
    files:
      - name: 'FAQ'
        label: 'FAQ'
        file: 'content/FAQ.md'
        create: false
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'programme'
    label: 'Programme'
    files:
      - name: 'programme'
        label: 'Programme'
        file: 'content/programme.md'
        create: false
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'editions-precedentes'
    label: 'Éditions précédentes'
    files:
      - name: 'editions-precedentes'
        label: 'Éditions précédentes'
        file: 'content/editions-precedentes.md'
        create: false
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'artistes'
    label: 'Artistes'
    folder: 'content/artistes'
    create: true
    slug: '{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: "Image d'accroche", name: "cover", widget: "image" }
