baseURL: https://claviersdanslesmonts.fr
languageCode: fr
title: Claviers Dans Les Monts
theme: cdlm
defaultContentLanguage: fr
buildFuture: true
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  current: 2022
  edition: "2ème"
  date: "10 et 11 Juin 2022"
  number: "06.07.74.56.21"
  helloasso: https://www.helloasso.com/associations/ensemble-cobalt
  stage: true
  theme:
    banner_bg: "#a3a3a3"                                                                                                             
    banner_text: "#ffffff"                                                                                                            
    body_text: "#220d00"                                                                                                              
    body_bg: "#828282"
    container: "70vw" 
